In [1]:
import numpy as np
import matplotlib.pyplot as plt



In [11]:
g_new = np.load('scratch/optimize/g_new.npz')
g_new.__dict__

{'_files': ['fmt.npy', 'vp_kernel.npy', 'vs_kernel.npy'],
 'files': ['fmt', 'vp_kernel', 'vs_kernel'],
 'allow_pickle': False,
 'pickle_kwargs': {'encoding': 'ASCII', 'fix_imports': True},
 'zip': <zipfile.ZipFile file=<_io.BufferedReader name='scratch/optimize/g_new.npz'> mode='r'>,
 'f': <numpy.lib.npyio.BagObj at 0x7fd47f66a610>,
 'fid': <_io.BufferedReader name='scratch/optimize/g_new.npz'>}

In [14]:
g_new.allow_pickle = True

In [15]:
g_new['vp_kernel']

array([array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.])], dtype=object)

In [9]:
checkpoint = np.load('scratch/optimize/checkpoint.npz')
checkpoint.__dict__

{'_files': ['restarted.npy',
  'func_vals.npy',
  'step_lens.npy',
  'gtg.npy',
  'gtp.npy',
  'step_count.npy',
  'step_len_max.npy',
  'LBFGS_iter.npy',
  'memory_used.npy'],
 'files': ['restarted',
  'func_vals',
  'step_lens',
  'gtg',
  'gtp',
  'step_count',
  'step_len_max',
  'LBFGS_iter',
  'memory_used'],
 'allow_pickle': False,
 'pickle_kwargs': {'encoding': 'ASCII', 'fix_imports': True},
 'zip': <zipfile.ZipFile file=<_io.BufferedReader name='scratch/optimize/checkpoint.npz'> mode='r'>,
 'f': <numpy.lib.npyio.BagObj at 0x7fd47f6f9c10>,
 'fid': <_io.BufferedReader name='scratch/optimize/checkpoint.npz'>}